name: Continuous integration/deployment
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"
jobs:

  server:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout estudo-graphql
        uses: actions/checkout@v1

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm install pg -g
          npm install

      - name: Lint
        run: npm run lint

      - name: Integrated test
        run: npm run test